version: "3.8"

services:
  db-affp:
    image: mariadb:11.4
    container_name: 
    restart: unless-stopped
    environment:
      MARIADB_DATABASE:
      MARIADB_USER: 
      MARIADB_PASSWORD: 
      MARIADB_ROOT_PASSWORD: 
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - affp_network

  symfony-backend-affp:
    build: ./backend
    container_name: symfony-backend-affp
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      DATABASE_URL: "mysql://affp:affp_password_change_me@db-affp:3306/affp?serverVersion=mariadb-11.4.0&charset=utf8mb4"
      STRIPE_SECRET_KEY: "CHANGE_ME"
      STRIPE_PRICE_ID: "CHANGE_ME"
      STRIPE_WEBHOOK_SECRET: "CHANGE_ME"
      MAILER_DSN: "CHANGE_ME"
      FRONTEND_URL: "https://africafactspress.com"
    depends_on:
      - db-affp
    volumes:
      - ./backend:/var/www/html
      - media_uploads:/var/www/html/public/uploads
    networks:
      - affp_network

  worker-affp:
    build: ./backend
    container_name: worker-affp
    restart: unless-stopped
    environment:
      APP_ENV: prod
      APP_DEBUG: "0"
      DATABASE_URL: "mysql://affp:affp_password_change_me@db-affp:3306/affp?serverVersion=mariadb-11.4.0&charset=utf8mb4"
      MAILER_DSN: "brevo+api://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@default"
      FRONTEND_URL: "https://africafactspress.com"
    depends_on:
      - db-affp
    volumes:
      - ./backend:/var/www/html
      - media_uploads:/var/www/html/public/uploads
    command: ["php", "bin/console", "messenger:consume", "async", "--time-limit=3600", "--memory-limit=256M"]
    networks:
      - affp_network

  react-frontend-affp:
    build: ./frontend
    container_name: react-frontend-affp
    restart: unless-stopped
    environment:
      NODE_ENV: "production"
      NEXT_PUBLIC_API_BASE_URL: "/api"
    command: ["npm", "run", "start", "--", "-p", "3000"]
    depends_on:
      - symfony-backend-affp
    networks:
      - affp_network

volumes:
  db_data:
  media_uploads:

networks:
  affp_network:
    external: true

